
GET https://httpbin.org/get HTTP/1.1

###
POST https://httpbin.org/get HTTP/1.1
accept: application/json

###
PUT https://httpbin.org/get HTTP/1.1
accept: application/json

###

PATCH https://httpbin.org/get HTTP/1.1
accept: application/json
###


DELETE  https://httpbin.org/get HTTP/1.1
accept: application/json


GET  https://httpbin.org/basic-auth/alpha/olomi HTTP/1.1
accept: application/json